### ISSUE TITLE
Socket - AJAX

### ISSUE THREAD

**Issue by matbandeli** [thegazou/Tsuro-Online#3]
- communiquer via des sockets sur Laravel en créant un jeu de base simple : 2 joueurs, lorsque le 1er clique sur ping, le 2e peut cliquer sur ping, lorsqu'il l'a fait, le 1er peut cliquer sur ping et ainsi de suite. (presque résolu) 
- actualiser la page via AJAX lorsque un joueur joue, c'est-à-dire quand il clique sur ping (en cours)

**Comment by greut** [comment]
@matbandeli :warning: les `websocket`s requierent d'avoir un port spécifique d'ouvert. Chose que le service informatique de l'école ne désire pas. Nous n'avons que le port 80 à disposition. Du coup, soit votre application ne fonctionne que quand on est connecté à l'école ou connecté au proxy. Ou vous vous y prenez autrement (qui serai mon conseil).

Un moyen simple alternatif est de faire de faire du polling avec jQuery.

``` javascript
function poll() {
   $.ajax({
       url: '/.../',
       dataType: 'json'
   }).done(function(json) {
       // traiter les données.
       // puis on retourne demander de l'info dans une seconde. 
       setTimeout(poll, 1000);
   })
}

$(document).ready(poll);
```

Souvent, les jeux ont un temps virtuel, qui peut être le tour de jeu dans votre cas. Le temps permet de s'assurer que tout le monde est à la même page.

**Comment by matbandeli** [comment]
Bonjour,

Merci pour la réponse rapide.
Les sockets vs le pooling. De ces 2 méthodes, les sockets avaient la préférence de M. Grunenwald lorsque nous lui en avions parlé il y a de cela quelques semaines, nous signifiant que le pooling consommait le serveur inutilement.
Le Pooling est plus simple, mais je pense poursuivre dans la direction des sockets, puisque j'arrive au bout (surtout la partie requête AJAX à terminer).

**Comment by greut** [comment]
Oui, j'entends bien et confirme la préférence de David.

Le problème est que les sockets ne vont pas fonctionner sur srvz sans être connecté au proxy et sans que je vous ouvre des ports entre votre serveur linux et srvz. Donc faites du polling, le serveur y survivra et ça sera un peu plus simple à mettre en œuvre (pour vous, moi et le service info).

**Configuration des serveurs**

```
Internet <-- 80 --> SRVZ (nginx) <-- port 800x : 80 --> Tsuro (nginx) <-- socket --> PHP-FPM
                                 <--- port 800x : 80 --> Admin (nginx) ...
                                 <---- port 800x : 80 --> Look4cards ...
```

**Comment by matbandeli** [comment]
C'est noté. Je vais faire ça avec du pooling.

**Comment by matbandeli** [comment]
Ca fonctionne à quelques bugs près (voir nouvelles issues)
